org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21
minecraft_version_range=[1.21, 1.22)
neo_version=21.0.167
neo_version_range=[21,)
loader_version_range=[4,)

mod_id=chromosomelib
mod_name=Chromosome Lib
mod_license=MIT
mod_version=0.0.1+1.21
mod_authors=Liu Dongyu, Artist1
mod_description=This mod aims to deeply expand the vanilla pet system, making cats and dogs more unique, engaging, and integrated into the player's journey.